### ISSUE TITLE
Parameters and Data for the Vanilla Baseline

### ISSUE THREAD

**Issue by Lenala39** [vita-epfl/trajnetplusplusbaselines#1]
Can anyone tell me whether the results of the vanilla baseline (that is compared to the submitted model to on AICrowd) are simply the LSTM with default parameters? And what data is this model trained on? Just the training data that is supplied by the challenge?

Thanks!

**Comment by theDebugger811** [comment]
Hello,
    The AICrowd baseline is proposed using the default LSTM parameters. The LSTM model was trained on all datasets (except the CFF ones)
