### ISSUE TITLE
Issue running social force

### ISSUE THREAD

**Issue by sanmoh99** [vita-epfl/trajnetplusplusbaselines#10]
Hi,
I can't run socialforce_eval.py because there are some files (pickle files in goals folder) which are not in the repo.
What are they and how can I run this code properly?

Thanks in advance.

**Comment by theDebugger811** [comment]
Hi @sanmoh99,
     Apologies for the late reply. You can run the socialforce model on any dataset using trajnet_evaluator:

python -m trajnet_evaluator --path <dataset_name> --sf

Hope this addresses your question.
