### ISSUE TITLE
Question about Visualizations of the decision-making of social interaction

### ISSUE THREAD

**Issue by xiran2018** [vita-epfl/trajnetplusplusbaselines#12]
Hello, I tried to draw dynamic pictures. According to the link you gave--https://github.com/vita-epfl/trajnetplusplusbaselines/tree/LRP, I opened it and looked at it, but I did not find the code for drawing dynamic pictures. Is there any error?

**Comment by theDebugger811** [comment]
Hello,
       The pictures are drawn using the [animate_lrp function](https://github.com/vita-epfl/trajnetplusplusbaselines/blob/585c0ce0e0ef728c1b1a58ccb82559a78c014e21/trajnetbaselines/lstm/utils.py#L182) which is being called in the LSTMPredictor function.

Thanks
Parth
