### ISSUE TITLE
How to generate the test_private file?

### ISSUE THREAD

**Issue by Kguo-cs** [vita-epfl/trajnetplusplusbaselines#13]
Hello. Can you tell me how to generate the test_private file? Thank you!

**Comment by Kguo-cs** [comment]
You only provide the test file in https://github.com/vita-epfl/trajnetplusplusdata/releases/tag/v4.0.

**Comment by theDebugger811** [comment]
We cannot provide the test_private file (it is hidden) as the test file provided is being used for judging the [AICrowd](https://www.aicrowd.com/challenges/trajnet-a-trajectory-forecasting-challenge) challenge.

You can generate a validation file using [create_validation.py](https://github.com/vita-epfl/trajnetplusplusbaselines/blob/master/create_validation.py) to find the best hyperparameters of the model. And later upload model predictions on AICrowd.

Thanks,
Parth
