### ISSUE TITLE
Issue about fast_evaluator and trajnet_evaluator

### ISSUE THREAD

**Issue by xieyunjiao** [vita-epfl/trajnetplusplusbaselines#15]
Hello,I've been using Trajnet ++  to evaluate trained models recently,
Whether I use fast_evaluator or trajner_evaluator, my col-I is always -1.
I read that part of the code, and the condition for col-I to occur is` num_gt_neigh ==num_predicted_neigh`. 
 But I don't know how I can modify the code to compute COL-I.
Thank you very much for answering my questions.

**Comment by theDebugger811** [comment]
Hello,
      Col-I results in a '-1' output when you don't predict all the neighbors present in the scene. Make sure you are predicting all the neighbors (and not ignoring any through functions like drop_distant). Also, as a workaround, you can comment num_gt_neigh ==num_predicted_neigh condition and keep enable_col1 to be True at all times. 
      
Note: If trajnet_evaluator gives Col-I to be -1, so will the AICrowd challenge evaluation.

**Comment by xieyunjiao** [comment]
Thank you very much for your tips. 
Which part of the code should I focus on so that my training model can predict the location of all the neighbors at the same time?
Does Trajnet ++ provide this capability, or should my model code make simultaneous predictions?
