### ISSUE TITLE
Issue about plot_log.py

### ISSUE THREAD

**Issue by xieyunjiao** [vita-epfl/trajnetplusplusbaselines#18]
Dear Author,
When I use plot_log.py,only the resulting accuracy picture is blank.The name is  `xx.val.png`.
As shown in the figure below:
![image](https://user-images.githubusercontent.com/54607003/119346893-5a0c3880-bccd-11eb-8d9c-7551494c40b3.png)
What should I do to make the accuracy show up correctly?
Thank you for your reply.

**Comment by theDebugger811** [comment]
The accuracy plot is redundant. It will be removed soon.

You can use the trajnet_evaluator or fast_evaluator to calculate the accuracy metrics.

**Comment by xieyunjiao** [comment]
> The accuracy plot is redundant. It will be removed soon.
> 
> You can use the trajnet_evaluator or fast_evaluator to calculate the accuracy metrics.

Okay, thank you.
