### ISSUE TITLE
Can't compute collision percentages for Kalman Filter baseline

### ISSUE THREAD

**Issue by pedro-mgb** [vita-epfl/trajnetplusplusbaselines#19]
Hello. Hope everyone that is reading this is doing well.

I was trying to run the trajnet evaluation code for the [Kalman filter](https://github.com/vita-epfl/trajnetplusplusbaselines/blob/master/trajnetbaselines/classical/kalman.py) implementation, but I get "-1" for the Col-I metric. 

From what I read in #15 , this is because the number of predicted tracks for the neighbours is not equal to the number of ground truth tracks. Upon closer inspection, I was obtaining additional elements on the list of tracks, that corresponded to empty lists (no actual positions).

While I'm not sure why this happened, I think it might be related to [this issue](https://github.com/vita-epfl/trajnetplusplusdataset/issues/8), where the start and end frames for different scenes are not completely separate, for the converted data using the [Trajnet++ dataset]((https://github.com/vita-epfl/trajnetplusplusdataset) code.

Can someone confirm that that is the case? I'm assuming I'm not the only one to have come accross this issue. I could make a script to perform such separation, and see if that is the actual problem. If I don't find any existing code to do so, I suppose that's my best option.

**Comment by theDebugger811** [comment]
Hello Pedro,
       You are indeed correct that the error is because the number of predicted tracks for the neighbours is not equal to the number of ground truth tracks. This error occurs when you keep the test split to be the same as the test_private datsplit. 

To answer in more detail, the test_private split might contain pedestrians that appear _after_ the observations, while the test split (generated using TrajNetplusplusdataset) does not contain these pedestrians. The trajnet_evaluator rectifies this issue when the test_private split != test split. 

However, if you wish to keep the test split == test_private split, you can circumvent this issue by manually setting _enable_col1_ flag to be always True in the trajnet_evaluator. Hope this addresses your question.

**Comment by pedro-mgb** [comment]
Forcing the `enable_col1` to True did the trick. Thank you!

I'll leave the issue open in case anyone also has this issue. But feel free to close it if you wish.

Have a good day!
