### ISSUE TITLE
predictions using classical model

### ISSUE THREAD

**Issue by Harsha-madyastha** [vita-epfl/trajnetplusplusbaselines#2]
How to get predictions from a kalman filter?

**Comment by theDebugger811** [comment]
Hello,
   Adding the --kf flag in evaluator allows this. Similar for Social Force and ORCA. 

Eg. python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path> --kf

**Comment by Harsha-madyastha** [comment]
Hello,
As per the code we do not Train the Kalman model so we will not have a .pkl
file to give it to the —output path , so what should we give as the —output
.
Have a Great day!
Best Regards,
Harsha Manjunath

**Comment by theDebugger811** [comment]
You do not have to provide any output path for Kalman Filter. Just the flag --kf will suffice.
For more details, you can refer to write.py in evaluator and the predict function in kalman.py

**Comment by marcos452** [comment]
> You do not have to provide any output path for Kalman Filter. Just the flag --kf will suffice.
> For more details, you can refer to write.py in evaluator and the predict function in kalman.py

Hello,
I use this command(Eg. python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path> --kf), but there is some errors occur. Could u help me?
![image](https://user-images.githubusercontent.com/63551534/89120946-d4f43080-d4ba-11ea-960e-1dc3975faf30.png)

Have a Great day!
Best Regards,
Marcos

**Comment by marcos452** [comment]
> You do not have to provide any output path for Kalman Filter. Just the flag --kf will suffice.
> For more details, you can refer to write.py in evaluator and the predict function in kalman.py

hello,
I use your command(python -m evaluator.trajnet_evaluator  --output <model_path> --lstm), and then I get some results about predictions in following picture.


![image](https://user-images.githubusercontent.com/63551534/89124359-b0a64d00-d4d6-11ea-84d6-ec463876251e.png)
test_results and test_pred are generated by the command. But why test_pred is empty? 
And then I want to visualize the prediction, but for the visualize_predictions.py, which command should I use?
should dataset_files come from test_reulsts or test_pred?

Have a Great day!
Best Regards,
Marcos

**Comment by theDebugger811** [comment]
Hello,
     The evaluator command is as follows: python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path>
(Do NOT provide --lstm command). 
To know more options about evaluator: 
python -m evaluator.trajnet_evaluator --help
If the command is correct, the test_pred file should not be empty. Make sure test private is not EMPTY.

To visualize the predictions, use the following command:
python -m evaluator.visualize_predictions DATA_BLOCK/<dataset_name>/test_private/<file_name> DATA_BLOCK/<dataset_name>/test_pred/<model_name>/<file_name>

**Comment by marcos452** [comment]
> Hello,
> The evaluator command is as follows: python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path>
> (Do NOT provide --lstm command).
> To know more options about evaluator:
> python -m evaluator.trajnet_evaluator --help
> If the command is correct, the test_pred file should not be empty. Make sure test private is not EMPTY.
> 
> To visualize the predictions, use the following command:
> python -m evaluator.visualize_predictions DATA_BLOCK/<dataset_name>/test_private/<file_name> DATA_BLOCK/<dataset_name>/test_pred/<model_name>/<file_name>

Hello,
Thanks for your reply.
But I use command (python -m evaluator.trajnet_evaluator --data /Users/llmlovejly/PycharmProjects/trajnet++/dest_new/test/biwi_hotel.pkl  --output  /Users/llmlovejly/PycharmProjects/trajnet++/trajnetbaselines/lstm/OUTPUT_BLOCK/trajdata/lstm_vanilla_None.pkl
). It occurs some errors in the following picture.
![image](https://user-images.githubusercontent.com/63551534/89129336-eeb66780-d4fc-11ea-8497-a5e4f456c595.png)
But I use command(python -m evaluator.trajnet_evaluator --output <model_path> --lstm), test_results and test_pred are generated by the command. But test_pred is empty.
Could u help me?

Have a great day!
Best Regards,
Marcos

**Comment by marcos452** [comment]
> Hello,
> The evaluator command is as follows: python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path>
> (Do NOT provide --lstm command).
> To know more options about evaluator:
> python -m evaluator.trajnet_evaluator --help
> If the command is correct, the test_pred file should not be empty. Make sure test private is not EMPTY.
> 
> To visualize the predictions, use the following command:
> python -m evaluator.visualize_predictions DATA_BLOCK/<dataset_name>/test_private/<file_name> DATA_BLOCK/<dataset_name>/test_pred/<model_name>/<file_name>

Hello,
Thanks for your reply.
But I use the command as follows: python -m evaluator.trajnet_evaluator --data <data_path> --output <model_path>, it occurs some error in following picture:
![image](https://user-images.githubusercontent.com/63551534/89130553-11994980-d506-11ea-9829-18f8417e5198.png)
So I check the help, there is no --data command, and I use the command as follows:  python -m evaluator.trajnet_evaluator --path trajdata  --output  /Users/llmlovejly/PycharmProjects/trajnet++/trajnetbaselines/lstm/OUTPUT_BLOCK/trajdata/lstm_vanilla_None.pkl.
The result shows the following picture:
![image](https://user-images.githubusercontent.com/63551534/89130624-aa2fc980-d506-11ea-8350-bbfded0a58f0.png)
finally, It seems to work successfully, but the test_pred file still EMPTY. There is just empty file lstm_vanilla_None. It shows the following picture. My test private is not EMPTY.
![image](https://user-images.githubusercontent.com/63551534/89130679-18748c00-d507-11ea-8266-85cd6670a7a5.png)

Have a great day!
Best Regards,
Marcos

**Comment by theDebugger811** [comment]
Hello,
      Yes, the correct command is: python -m evaluator.trajnet_evaluator --path <data_path> --output <model_path>
(updated in the README.)

Regarding the test_pred (model predictions file), as mentioned in https://github.com/vita-epfl/trajnetplusplusbaselines/tree/master/evaluator Point 2., the model skips writing if test_pred file already exists (from a previous run). You need to delete the test_pred file and rerun the command.

**Comment by marcos452** [comment]
> Hello,
> Yes, the correct command is: python -m evaluator.trajnet_evaluator --path <data_path> --output <model_path>
> (updated in the README.)
> 
> Regarding the test_pred (model predictions file), as mentioned in https://github.com/vita-epfl/trajnetplusplusbaselines/tree/master/evaluator Point 2., the model skips writing if test_pred file already exists (from a previous run). You need to delete the test_pred file and rerun the command.

Hello,
Thanks for your reply.
But I meet a confusing bug, it shows in the following picture. 

![image](https://user-images.githubusercontent.com/63551534/89159389-b4d27900-d56f-11ea-91f4-bcb8cae1cdc6.png)
Ths modul lstm can't be found. I check the path that is right. This means the model can't be loud so that the test_pred file is empty.
I am trying to change the way of loading the model.
Could u give me some advice?
Have a great day!
Best Regards,
Marcos

**Comment by theDebugger811** [comment]
Hello,
     It seems that the error arises because of the location of OUTPUT_BLOCK folder. OUTPUT_BLOCK should be present inside the 'trajnetbaselines' folder and not the 'lstm' folder.

**Comment by marcos452** [comment]
> Hello,
> It seems that the error arises because of the location of OUTPUT_BLOCK folder. OUTPUT_BLOCK should be present inside the 'trajnetbaselines' folder and not the 'lstm' folder.

I change the path of the OUTPUT_BLOCK folder, the bug still occurs. I am confused again.

Have a great day!
Best Regards,
Marcos

**Comment by theDebugger811** [comment]
Hello,
     The OUTPUT_BLOCK (if the code is run correctly) should automatically be created in trajnetbaselines folder.

It might be helpful to refer to the [kickstarter blog](https://thedebugger811.github.io/posts/2020/03/intro_trajnetpp/).
