### ISSUE TITLE
 FDE score of 1.14 with social LSTM

### ISSUE THREAD

**Issue by Mirorrn** [vita-epfl/trajnetplusplusbaselines#21]
Hi!
I am trying to get the FDE score of 1.14 with social LSTM.

Did you train on the whole (with cff) training dataset?
How many epochs?
And with which parameters?

Thanks in advance
Many greetings

**Comment by theDebugger811** [comment]
Hello,
 
Please refer to the following issue: https://github.com/vita-epfl/trajnetplusplusbaselines/issues/6
The training was done without using cff training dataset.
