### ISSUE TITLE
Data normalization? Minor errors and minor suggestions

### ISSUE THREAD

**Issue by tmralmeida** [vita-epfl/trajnetplusplusbaselines#23]
Hi,

First of all congratulations on this fruitful work. 

Then, I have a technical question. It seems that you don't **normalize** the data in any of the steps. Thus, why did you choose the standard Gaussian noise? It should provide samples with high variance wrt to k. 

After downloading and installing the social force simulator, I ran the trainer and it threw an **error**:
`ModuleNotFoundError: No module named 'socialforce.fieldofview'`

After changing to:
`from socialforce.field_of_view import FieldOfView`

Everything worked fine.

**Comment by theDebugger811** [comment]
Hi, 
    Thanks for pointing out the SocialForce error. It's due to the change in the source repository. It has been updated.

Regarding the Gaussian noise question, can you be more specific about which part of the code you are referring to?

Thanks,
Parth

**Comment by tmralmeida** [comment]
HI,

Thanks for the answer. Never mind, I could understand.

Tiago
