### ISSUE TITLE
Challenge submission: "No more retries left"

### ISSUE THREAD

**Issue by S-Hauri** [vita-epfl/trajnetplusplusbaselines#29]
I just submitted a zip file with my predictions to the AIcrowd challenge. However, the submission failed with the message: "No more retries left". What does this mean?

**Comment by theDebugger811** [comment]
Hi S-Hauri,
      The submission limit on AICrowd maximum 50 submissions/day. I have edited it to 5000 submission/day. 

Hope you do not face this issue anymore.
