### ISSUE TITLE
Question: What is layer_dims parameter?

### ISSUE THREAD

**Issue by pedramkho** [vita-epfl/trajnetplusplusbaselines#4]
I'm aiming to train a Social LSTM model, but I keep getting an error regarding this parameter (which is "None" by default).

**Comment by theDebugger811** [comment]
The layer_dims parameter is the dimension of the hidden-layer of the MLP encoding the social grid tensor. (Preferrable value for Social LSTM is 1024). 
A commented version of code is available here: https://github.com/vita-epfl/trajnetplusplusbaselines/blob/batching/trajnetbaselines/lstm/gridbased_pooling.py
Will be merged with the master soon.
