### ISSUE TITLE
Hyper parameters

### ISSUE THREAD

**Issue by sanmoh99** [vita-epfl/trajnetplusplusbaselines#6]
Hi, I want to train social-LSTM model on ETH and UCY datasets. Would you mind sharing the best hyper parameters that achieve the results stated in the paper?

Thanks in advance

**Comment by theDebugger811** [comment]
Hello,
     Here is the command line to get the results of Social LSTM on TrajNet++ data.

python -m trajnetbaselines.lstm.trainer --augment --type social  --epochs 25 --step_size 10 --n 16 --cell_side 0.6 --embedding_arch conv_two_layer --layer_dims 1024 --batch_size 8 --loss 'pred'

Thanks
Parth
