### ISSUE TITLE
How to visualize the predicted trajectories?

### ISSUE THREAD

**Issue by viettiepx2** [vita-epfl/trajnetplusplusbaselines#8]
Hi, I want to visualize the predicted trajectories, ike the pictures in the article, can you help me?

**Comment by theDebugger811** [comment]
Hi,
   Could you let me know which article are you referring to?

**Comment by viettiepx2** [comment]
Hi
I want to visualize predicted trajectory of human in real-time, using
social LSTM. But it's difficult for me because I'm a newbie. Can you help
me?

**Comment by theDebugger811** [comment]
Hello,
    You can go through this [link](https://thedebugger811.github.io/posts/2020/03/intro_trajnetpp/) for instructions to visualize models.
