### ISSUE TITLE
No module named 'socialforce' ??

### ISSUE THREAD

**Issue by moonsh** [vita-epfl/trajnetplusplusbaselines#9]
Hi, first of all, thank you for sharing this great work.

"python -m trajnetbaselines.lstm.trainer --type directional --augment"
I just ran this command but I have faced the below error.
No module named 'socialforce'

Is there something I should do install or include?
Thank you,

**Comment by theDebugger811** [comment]
Hello,
      You can follow this [link](https://thedebugger811.github.io/posts/2020/03/intro_trajnetpp/) to set up TrajNet++. It has instructions to install dependencies like socialforce, rvo2.

**Comment by moonsh** [comment]
Yes. Thank you. It works well.
